### ISSUE TITLE
video1 笔记(flex 默认布局, box-sizing, vh高度单位 viewport height)

### ISSUE THREAD

**Issue by shaohailong** [shaohailong/flex#1]
# 知识点整理
1. nromalize.css 进行一些基本的初始化动作, 因为各个浏览器对于很多元素的默认呈现方式, 并不合理
2. box-sizing 盒子模型, 统一使用 border-box 会避免很多很多问题, 按道理也应当属于 normallize的一部分, 示例代码:
   
   ``` css
   * {-moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box;}
   ```
3. 高度单位: vh 意思是 viewport height, 100vh 的意思是 百分百的 viewport height, 示例代码:
   
   ``` css
   .container {
   display: inline-flex;
   border: 10px solid goldenrod;
   height: 100vh;
   }
   ```
4. display: inline-flex; 会让我们的flex 模块是行内的元素, 其外部的包装层, 也会紧紧的贴合到内容上.
